version: '3.5'
services:
  flask:
    container_name: application
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile-Prod
    volumes:
      - .:/application
    ports:
      - "5000:5000"
